server:
  port: 8079

spring:
  application:
    name: finbridge-api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**

        - id: account-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/accounts/**

        - id: transaction-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/transactions/**

        - id: reporting-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/reports/**,/api/v1/stats/**

        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/payments/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
      enabled: true
    gateway:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
      service: api-gateway
      environment: development
      team: finbridge

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.finbridge: INFO
    org.springframework.cloud.gateway: INFO
    io.micrometer: INFO
