server:
  port: 8081

spring:
  main:
    allow-circular-references: true

  application:
    name: finbridge-user-service

  datasource:
    url: jdbc:h2:mem:finbridge
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

jwt:
  secret: myFinBridgeSecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.finbridge: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
